dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    secure: Yh/aQJF92OXcWPm7o6JdkWGPQI9vHb+nktaWzEQdXWNBIg9jX4jEbbygdUfarCtSSlITxPFZnyc0xtqkOzTHyuFi9+lBoY3di9SkwAQA+1Okv5CQkLp6rCuwonmdI3u2kNiVxCC3/y6h4REzpuObGKMLLGW/MVvMTC90vq9AU9DG/NAJzD1MwBaH8RNKAdrWH7O7qOv8oR+lQULTI624y0I+PsQFUT0e5qLtqzaBB+h15E1wCXvjum0p6Llt1IbZKO/TkURjv5K/JdeR0DTxhbqEmmFBdH7Rtj8WecxvJ+lTgGRkzuvgyrTCRbEQ6O2JyFMvOMoqxDVo6Vb7m2Zg8vmdYiVXAtGy1NQAjEi3W5YPSb5sEzZWP3c8NCrcX65Sn1q+06DCg3uttDCY76Rncf2uGdcTTbNnKNCThIEcfmkSg44haSogIHHO3cwhrh2u5oXykqdPLJpbi5oqjhDCoADO5PfUGBUzjv/nDpSMFvCv+9nSDmPIX92VNNUrVvnCTYecOmHkuI6NvutrmtpVsienUGxVojZU6BD9P7Xbf5NwezAEJKujfY2WcEL+JWzd6sTWBToD1Kw6WX6qyedHzjuqUPmRoOR/KabYVs/x2Ltl/GwVth9XfmnmGhJC96WD2mstnWaFVSXPmevXbq1f58r8CeMXsFsFdSe99llyM+Y=
